# Generated by Django 3.1.7 on 2021-03-14 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artist_name', models.CharField(max_length=200)),
                ('song', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=-1)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musey.artists')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musey.users')),
            ],
        ),
    ]
