# Generated by Django 3.1.7 on 2021-03-14 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musey', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Artists',
            new_name='Songs',
        ),
    ]
