# Generated by Django 3.1.7 on 2021-03-15 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musey', '0002_auto_20210314_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('artist_name', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('astrological_sign', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='songs',
            name='artist_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musey.artists'),
        ),
    ]
