# Generated by Django 3.1.7 on 2021-03-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musey', '0003_auto_20210315_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='birthplace',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artists',
            name='genre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artists',
            name='astrological_sign',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
