# Generated by Django 3.1.7 on 2021-03-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musey', '0004_auto_20210315_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='astrological_sign',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artists',
            name='birthplace',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artists',
            name='genre',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
